#!/usr/bin/env python3
"""tools/faithfulness_gate.py — proves the public-face cutover loses NO content.

This replaces a human diff-review. It asserts that every timeline entry that existed in the
PREVIOUS (committed) docs/index.html still has its substantive text present in the NEWLY GENERATED
docs/index.html. Layout/markup may change; words may not. Zero content loss is the bar.

  old = git show <ref>:docs/index.html   (default: HEAD — the hand-authored page)
  new = working-tree docs/index.html     (just generated by build_site.py)

Exit 0 = every old entry's title + body text is preserved in new.
Exit 1 = at least one entry lost text; prints exactly what's missing. (Caller must NOT merge.)

Usage: python3 tools/faithfulness_gate.py [old_ref]
"""
from __future__ import annotations
import html
import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent


def visible(s: str) -> str:
    s = re.sub(r"<[^>]+>", " ", s)
    s = html.unescape(s)
    return re.sub(r"\s+", " ", s).strip()


def old_index(ref: str) -> str:
    return subprocess.check_output(["git", "show", f"{ref}:docs/index.html"], cwd=REPO, text=True)


def timeline_entries(page: str):
    """Yield (title_text, body_text) for each tl-entry in the timeline region."""
    try:
        region = page[page.index('<div class="timeline">'):page.index("</section>", page.index('<div class="timeline">'))]
    except ValueError:
        region = page
    for block in re.findall(r'<article class="tl-entry[^"]*">(.*?)</article>', region, flags=re.S):
        h3 = re.search(r"<h3>(.*?)</h3>", block, re.S)
        ps = re.findall(r"<p>(.*?)</p>", block, re.S)
        title = visible(h3.group(1)) if h3 else ""
        body = visible(" ".join(ps))
        yield title, body


def main(argv) -> int:
    ref = argv[1] if len(argv) > 1 else "HEAD"
    old = old_index(ref)
    new_path = REPO / "docs" / "index.html"
    new_visible = visible(new_path.read_text(encoding="utf-8"))

    old_entries = list(timeline_entries(old))
    missing = []
    for i, (title, body) in enumerate(old_entries):
        for label, txt in (("title", title), ("body", body)):
            if txt and txt not in new_visible:
                missing.append((i, label, txt))

    print(f"faithfulness gate: {len(old_entries)} timeline entries in {ref}:docs/index.html")
    if not missing:
        print(f"✓ PASS — all {len(old_entries)} entries fully preserved in the generated page (0 content lost).")
        return 0

    print(f"✗ FAIL — {len(missing)} piece(s) of entry text are MISSING from the generated page:")
    for i, label, txt in missing[:20]:
        snippet = txt[:120] + ("…" if len(txt) > 120 else "")
        print(f"   entry #{i} [{label}]: {snippet}")
    return 1


if __name__ == "__main__":
    sys.exit(main(sys.argv))
